#
# Makefile for usbpd devices
#

obj-$(CONFIG_CCIC_S2MU004)	+= s2mu004-usbpd.o
obj-$(CONFIG_USE_CCIC)		+= usbpd.o usbpd_cc.o
obj-$(CONFIG_USE_CCIC)		+= usbpd_policy.o usbpd_manager.o pdic_notifier.o
obj-$(CONFIG_CCIC_NOTIFIER)		+= ccic_notifier.o ccic_sysfs.o
